- name: Build Docker Image for Laravel App
  hosts: all
  become: yes
  tasks:
    - name: Build Docker image for node-server
      community.docker.docker_image:
        name: Project7
        source: build
        build:
          path: /path/to/your/Project7/
        state: present
        force_source: yes

    - name: Build Docker image for phpmyadmin
      community.docker.docker_image:
        name: phpmyadmin
        source: pull
        state: present
